name: Run cucumber test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@latest

      - name: Build and run tests
        run: mvn clean test